" generally refer to: https://github.com/esm7/obsidian-vimrc-support
" To test file, write file and run "reload app without saving"
" 
" To use an obsidian command (see back, forward example):
" - Use Ctrl+Shift+I to open the dev console
" - reload and type :obcommand. The names are now in the Console (2nd tab).
" - note, can't rebind exmap-obmap commands with map
" Also execute codemirror commands with cmcommand, js with jscommand.
"
" Note about `surround`: as of 2022-05-20, surround does not work, and is janky
" anyhow, but there's a fix coming, eventually, maybe.


" Yank to system clipboard https://forum.obsidian.md/t/how-to-copy-with-vim-mode/3881
set clipboard=unnamed

" alt escapes if I forget to escape
imap jj <Esc> 
imap kk <Esc>

" Bind C-u, C-d (up, down) to Shift-U and shift-D, so that C-u and C-d can be used for normal Obsidian hotkeys.
" Use C-z, C-S-z for undo/redo.
nmap U <C-u>
nmap D <C-d>
" free up C-r for search-replace, set redo to vim-redo
nmap <C-Z> <C-r> 
" Bind C-o, C-i (jump back, forward) to Shift-E and shift-B for same
nmap E <C-i>
nmap B <C-o>

" Since C-o is taken, use the following for go-back/forward.
" This mapping repeats a mapping in the in-app hotkeys menu for demonstration; the in-app menu overwrites mappings here.
exmap back obcommand app:go-back
nmap <A-,> :back
exmap forward obcommand app:go-forward
nmap <A-.> :forward

" enable select all with C-a
unmap <C-a>

" be able to type gL or dL to delete rest of line
nmap H ^
omap H ^
nmap L $
omap L $

" transpose, shift case
nmap t xhhpll 
nmap T ~ 

" Example leader mapping, set '-' as leader
" may migrate to this if the Leader-Hotkeys normal-mode bug isn't fixed
nmap - <leader>
nmap <leader>j 4j
nmap <leader>k 4k

""" Trash
" - useless, not sure how to get rid of Obsidian's persistent search highlight, except hit esc every time
" nmap <F9> :nohl 
" set nohlsearch 
